issue-3-user-can-save-artwork
bernardinoa/ajax-project pull request #8
Opened 2021-09-29 23:57 UTC by bernardinoa

https://user-images.githubusercontent.com/88168364/135364161-bd99495a-26fa-46da-826a-5ce4578de811.mp4

2021-09-30 00:01 UTC, codingcodymiller requested changes

2021-09-30 00:01 UTC, codingcodymiller commented on js/main.js
> +    }
You should make this event handler a named function.

2021-09-30 00:01 UTC, codingcodymiller commented on js/main.js
> +      save($save);
This function definition isn't really adding anything. If anything, the name `save` is overly reductive, I'm not sure what its purpose is. You should just add the event listener here in this function.

2021-09-30 00:02 UTC, codingcodymiller requested changes

2021-09-30 00:02 UTC, codingcodymiller commented on js/main.js
> +      $checkmarkPath.setAttributeNS(null, 'd', 'M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997
What is the purpose of all this? Why not just use icons from FontAwesome?

2021-09-30 00:13 UTC, bernardinoa commented on js/main.js
> +      $checkmarkPath.setAttributeNS(null, 'd', 'M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997
that's a good point - i opted towards doing it this way since importing the fontawesome stylesheet adds weight to the application. a possible alternative would have been to [download the entire fontawesome toolkit and host it myself](https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/hosting-font-awesome-yourself) but that would also be excessive considering i'm only using 3 icons 

[it's related to one of the things i had as a task on my issue 3](https://github.com/bernardinoa/ajax-project/issues/3), namely: `replace search icon from fontawesome with an actual search icon svg to offload weight; delete the imported fontawesome stylehseet`

2021-09-30 00:49 UTC, bernardinoa commented on js/main.js
> +      save($save);
the purpose of the function reference here is to be able to use the `$save` button element and whatever is within that element (the `$plus` icon/element and the `$checkmark` icon/element) outside it's function in the `save` function (now renamed to `saveArtwork` in the latest commit) which has a nested event listener function within it for that `$save` button reference; hence the `button` parameter

disregarding what i said previously, i tried adding the `save` (again, now `saveArtwork`) event listener within the loop which iterates through each record and where the dom manipulation is occurring but a few things happen:
1. given that the dom manipulation function code block occurs once, i am only able to save one piece of artwork
2. when i save a piecework (which, again, can only happen once), the plus icon stays put - meaning, the plus icon doesn't change to the checkmark icon when i save that one artwork

2021-09-30 16:28 UTC, codingcodymiller commented on js/main.js
> +      $checkmarkPath.setAttributeNS(null, 'd', 'M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997
Hey Bernie, thank you for the explanation! I must have missed that task item in your Issue, thank you for showing me. You misunderstood what I had meant by "weight" at that point, I had meant for it to be interpreted as synonymous with "busy". The gif would be visually intense when mixed with your primary content being images.

In regards to this issue specifically, the added complexity to your JavaScript is not worth what loading time you might save for not importing FontAwesome. The FontAwesome stylesheet will take about 30-40ms to load into your page, aka .003 seconds. I think you can afford it 🤓 
![image](https://user-images.githubusercontent.com/32880187/135494523-b4fdb331-90ea-4ac7-b079-86bee864ea5a.png)

2021-09-30 16:37 UTC, codingcodymiller commented on js/main.js
> +      save($save);
What I am referring to here is that the `addEventListener` method you are calling within the `saveArtwork` function can just be relocated in full to the `load` event handler for your `xhr` in the `request` function. There is no reason this should need to be in a separate function block entirely. If relocating this code breaks anything in your application, feel free to show me the behavior via Slack, and I can help you address it.

This code:
![image](https://user-images.githubusercontent.com/32880187/135495392-1d928d2c-c9ea-47db-b249-9e892e461666.png)


Additionally, this function definition which is being used as your `load` event handler is **_immense_**. There is no reason it should be an anonymous function. Please make it a named function. Additionally, you should not create named functions as arguments in a method call, it is hard to locate the function in the file, and it could make that function accidentally dependent on variables from a parent scope. Please declare all named functions within the global scope. Again, if this breaks anything in your code, feel free to reach out. It would likely mean you are using a value for a parent scope that you should actually be passing as an argument to the function definition.

2021-09-30 16:38 UTC, codingcodymiller commented on js/main.js
> +    }
Please move this named function to the global scope, don't just name it in place as an argument.

2021-10-01 22:54 UTC, thebearingedge approved these changes

2021-10-01 22:56 UTC, merged